# Generated by Django 5.2.6 on 2025-10-31 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0010_faqquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('question', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
