# Generated by Django 5.2.6 on 2025-10-31 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0011_employeequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeequestion',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
