# Generated by Django 5.2.6 on 2025-11-07 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0012_employeequestion_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='epass_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
