# Generated by Django 5.2.6 on 2025-11-11 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0013_enrollmentrequest_epass_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollmentrequest',
            name='epass_number',
        ),
        migrations.AddField(
            model_name='enrollmentrequest',
            name='pass_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
