# Generated by Django 5.2.6 on 2025-11-14 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport_app', '0014_remove_enrollmentrequest_epass_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentrequest',
            name='sub_role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentrequest',
            name='role',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Other', 'Other')], max_length=20),
        ),
    ]
